### ISSUE TITLE
v1.119.14.127-alpha is the release version, but the version number 1.118.14.127 in server extender

### ISSUE THREAD

**Issue by afinegan** [rexxar-tc/SEServerExtender#12]
v1.119.14.127-alpha is the release version, but the version number 1.118.14.127 in server extender

Its stopping the auto update that I am using with Space Engineer Server manager - the versions need to be the same so the updater works lol

**Comment by rexxar-tc** [comment]
This isn't really my problem. I did forget to update the internal version number, but if that's causing SESM to have a fit, they're doing something very wrong. I'll go have a chat with the SESM developer.

**Comment by afinegan** [comment]
It keeps saying there is an update, and when I run it - it says map is created with a newer version and SESE stops.
