### ISSUE TITLE
only add  MyObjectBuilderType.RegisterAssemblies() not work

### ISSUE THREAD

**Issue by yajiedesign** [rexxar-tc/SEServerExtender#13]
must run MyObjectBuilderSerializer.RegisterAssembliesAndLoadSerializers() before load any setting.
but RegisterAssembliesAndLoadSerializers cannot be run repeatedly.
I am patched VRage.Game.dll  MyObjectBuilderSerializer.RegisterAssembliesAndLoadSerializers() add repeated operation detection fix it,

**Comment by rexxar-tc** [comment]
I'm sorry, I really have no idea what you mean.
