### ISSUE TITLE
Server Extender doesnt update mod changes completely

### ISSUE THREAD

**Issue by markam67** [rexxar-tc/SEServerExtender#15]
When I attempted to make a addition to the mods list within Server Extender it updates correctly in the config file but does not change the contents of the .SBS file in the Save directory. What this does is prevent the new mods from being loaded when the game map loads. I had to manually add those new mods to the save game file in order for the mods to load correctly.

**Comment by rexxar-tc** [comment]
SESE doesn't even look at the sbs. That is managed entirely by the game. When you add mods, you have to do it **before** you start the server. Otherwise the game won't know you've added mods and won't write them into the sbs. Be sure to hit save before you start the server.

**Comment by rexxar-tc** [comment]
SESE doesn't even look at the sbs. That is managed entirely by the game. When you add mods, you have to do it **before** you start the server. Otherwise the game won't know you've added mods and won't write them into the sbs. Be sure to hit save before you start the server.

**Comment by markam67** [comment]
In theory I would agree completely with what you are saying. However I did save repeatedly and manually examined the config file that is normally used to load and start the world and sure enough the new mod information was present but did not load when the world loaded. In fact the mods that downloaded did not even download the new mods. It was not until I manually edited the SBC in the save directory, not the SBS file, in the save game directory and changed the mod section there that the new added mods loaded correctly. I wonder if KEEN changed something about how the game loads?

**Comment by rexxar-tc** [comment]
Keen did change how the config is loaded, that's why I had to release that awful hack Thursday evening.

I dug deeper and it turns out that SESE does actually rewrite the sandbox.sbc. It currently isn't doing that because it can't load the config file before turning it into the sbc. I can fix the config loading, but for some reason the fix causes the server to not start.

I haven't the faintest idea what's going on, so I have no idea when it will get fixed.

**Comment by markam67** [comment]
Ok at least i am not losing my mind. :) And we know what you have to do to change mods.

**Comment by yajiedesign** [comment]
@rexxar-tc this bug becaue you must run MyObjectBuilderSerializer.RegisterAssembliesAndLoadSerializers() first.

**Comment by yajiedesign** [comment]
@rexxar-tc To fix the current , you need to modify the game files

**Comment by rexxar-tc** [comment]
Running RegisterAssemblies... fixes the problem, but it causes the server to crash on startup. I need to wait until Keen publishes the unregister method, probably next thursday.

If they don't publish the unregister method, I do have other options, but it will take a lot of time.

**Comment by yajiedesign** [comment]
I knew it would crash, because it couldn't run two times.you can add some repeat operation check in "RegisterAssembliesAndLoadSerializers" with mono cecil.
of course if keen can add it is better.

**Comment by rexxar-tc** [comment]
Fixed in the last update.
