### ISSUE TITLE
Reflection validation fails on startup

### ISSUE THREAD

**Issue by rexxar-tc** [rexxar-tc/SEServerExtender#2]
This is probably the root cause of issue #8 in Essentials.

**Comment by rexxar-tc** [comment]
Looks like most or all of these failures is caused by Keen removing various MySync methods and classes from the API. It isn't worth the trouble of squelching the startup error messages, so they stay.

We have to find equivalent methods for these inaccessible ones. Someone else can handle that.

**Comment by tdmike** [comment]
I might start looking into this after the holidays. I think I already identified some equivalent methodes, need to test them though. Will keep you up-to-date.

**Comment by rexxar-tc** [comment]
Awesome, thanks! Can I suggest looking at thrusters first? The huge amount of those that can exist on any grid is what causes issue #6. I think battery is the next biggest offender

**Comment by tdmike** [comment]
Yeah sure i'll look in to it after I wake up (its 02:20 am here)

**Comment by tdmike** [comment]
So just for reference posting the full starting error log: http://pastebin.com/QjUHgvTU

**Comment by tdmike** [comment]
@rexxar-tc so just had two weeks off but little time with christmas and new years around the corner. However I did get to work a little on the reflection errors, I have fixed the piston, reactor and landing gear errors. Though I cant seem to find out where the thrusters and batteries go wrong (Off course I know the origin of the error. I just can't seem to find the correct classes to connect with), do you have any suggestions in which direction I should look. At the moment I am at a total loss.

**Comment by rexxar-tc** [comment]
The problem with thrusters is that MyThrust.SyncObject no longer exists. As far as I can tell, this is really only used to set the thrust override. I took a look at the current game code, and I think simply setting m_thrustOverride.Value will sync automatically. Unfortunately that field is private and I haven't learned how reflection works yet....

As to batteries, ReceiveCurrentPowerPacket doesn't exist. I'm thinking that MySyncBatteryBlock() might contain what we need? Just a bunch of MySyncLayer.RegisterMessage stuff.

**Comment by rexxar-tc** [comment]
Actually, don't worry about this. I just spoke to Tyrsis, and the block proxies are all horribly old and outdated. It can all be replaced with ModAPI stuff, which should be vastly superior.

**Comment by rexxar-tc** [comment]
I'm going to close this now; I've started on a huge refactor that will solve all these issues
