### ISSUE TITLE
opening entity list causes severe ups drop

### ISSUE THREAD

**Issue by SilentSymphony** [rexxar-tc/SEServerExtender#6]
I've always noticed a slight drop in the server performance when navigating the entity list but recently it has been so severe as to take my server from 30-60 ups all the way down to 2-12 ups

Normally this is not a big issue as the entity list is not required for much, But occasionally i need to restore a ship for a player and does require me to open it.

I don't know if its possible to fix this right now or how complicated it is but i figured i would report it anyway.

**Comment by rexxar-tc** [comment]
As you said, this is an old issue. It's another of those things where Keen changed some code and SESE didn't keep up. In this case, SESE is looking for something about thruster networks, but the code doesn't exist in SE anymore. That means we throw an error for every single thruster on every single entity in the world.

It's non-critical, and likely to change with new netcode, so it's low-priority at the moment.

**Comment by rexxar-tc** [comment]
Closing as child of #2
